name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install mingw
      run: sudo apt-get -y install gcc-mingw-w64-i686 gcc-mingw-w64-x86-64  
    - name: Build
      run: make
  build-windows-cygwin:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download cygwin
        run: (New-Object System.Net.WebClient).DownloadFile("https://cygwin.com/setup-x86_64.exe", "setup-x86_64.exe")
      - name: Install cygwin
        run:
          $cygwin_root = Join-Path (Get-Item .).FullName cygwin64;
          .\setup-x86_64.exe -B -n -d -R $cygwin_root -s https://mirrors.kernel.org/sourceware/cygwin/ -q -P make mingw64-i686-gcc-core mingw64-x86_64-gcc-core;
      - name: Add cygwin into the PATH
        run: $env:Path += ";{0}\bin" -f $cygwin_root
      - name: Build
        run: make
