name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Install mingw
      run: sudo apt-get -y install gcc-mingw-w64-i686 gcc-mingw-w64-x86-64  
    - name: Build
      run: make
  build-windows-cygwin:
    runs-on: windows-latest
    steps:
      - name: Download cygwin
        run: (New-Object System.Net.WebClient).DownloadFile("https://cygwin.com/setup-x86_64.exe", "setup-x86_64.exe")
      - name: Install cygwin
        run:
          $cygwin_root = Join-Path (Get-Item .).FullName cygwin64;
          $process = Start-Process -Wait -PassThru -FilePath "setup-x86_64.exe" -ArgumentList ("-B -n -d -R {0} -q -P make mingw64-i686-gcc-core mingw64-x86_64-gcc-core" -f $cygwin_root);
          if ($process.ExitCode -ne 0) { throw "Failed to install cygwin." }
      - name: Add cygwin into the PATH
        run: $env:Path += ";{0}/bin" -f $cygwin_root
      - name: Build
        run:
          $process = Start-Process -Wait -PassThru -FilePath "make";
          if ($process.ExitCode -ne 0) { throw "Failed to run make." }
