name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-bionic
    steps:
    - uses: actions/checkout@v2
    - name: Install mingw
      run: sudo apt-get -y install gcc-mingw-w64-i686 gcc-mingw-w64-x86_64  
    - name: Build
      run: make
  build-windows-cygwin:
    runs-on: windows-latest
    steps:
      - name: Download cygwin
        run: (New-Object System.Net.WebClient).DownloadFile("https://cygwin.com/setup-x86_64.exe", "setup-x86_64.exe")
      - name: Install cygwin
        run: Start-Process -FilePath "setup-x86_64.exe" -ArgumentList "-P mingw64-i686-gcc-core mingw64-x86_64-gcc-core"
      - name: Add cygwin into the PATH
        run: $env:Path += ";C:\cygwin64\bin"
      - name: Build
        run: Start-Process -FilePath "make"
